# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-22 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobilenumber', models.IntegerField()),
                ('dateofbirth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
