# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-22 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mobilenumber',
            field=models.CharField(max_length=14),
        ),
    ]
