# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-22 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registerApp', '0002_auto_20201222_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='dateofbirth',
            field=models.DateTimeField(null=True),
        ),
    ]
